Algoritmo "EXERCICIO_6"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/05/2022
Var
   nome:caractere
   salario:real


Inicio
escreval("Informe seu nome : ")
leia(nome)
escreval("Informe seu salario : ")
leia(salario)

se(salario>1200)entao
escreval(nome," Seu salario e maior que um salario minimo!")
fimse


Fimalgoritmo