Algoritmo "EXERCICIO_10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/05/2022
Var
numero1: inteiro
numero2: inteiro


Inicio
numero2<- 1

escreval("Digite o numero :")
leia (numero1)

para numero2 de 1 ate 10  faca
     escreval(numero1, " x ", numero2, " = ", (numero1*numero2))
fimpara


Fimalgoritmo