Algoritmo "EXERCICIO_19"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/05/2022
Var
j:inteiro



Inicio
escreval("Imprimindo de 1 a 10 repita ate")
j<-1
repita
escreval(j)
j<-j+1
se j=5 entao
interrompa
fimse
ate j>10
escreval("Executando apos um INTERROMPA j=",j)
Fimalgoritmo