Algoritmo "EXERCICIO_10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/05/2022
Var
   numero1  : inteiro


Inicio
    escreval("multiplos de 0 a 100")

    para numero1 de 0 ate 100 passo +2 faca
         escreval(numero1)
    fimpara


Fimalgoritmo